### PR TITLE
Add Python 3.11 to supported versions

### PR DESCRIPTION
**Pull request by danielhuppmann**
Add Python 3.11 to supported versions

### CODE REVIEW

**Comment by danielhuppmann** [comment]
Ok, I have no idea why this PR is failing... Please help @meksor @phackstock @glatterf42!

**Comment by meksor** [comment]
My first guess: we might need the package python3.11-dev in the container used to run these checks.

**Comment by phackstock** [comment]
@meksor, seems like you're onto something https://github.com/aio-libs/aiohttp/issues/6600#issuecomment-1659592087.

**Comment by phackstock** [comment]
Installing python3.11-dev does not seem to be the solution... I'll keep on digging.

**Comment by phackstock** [comment]
@danielhuppmann, tests are finally running now. 
After some painful debugging I was able to fix it.
The issue seems to have been a package called `httptools` which is a dependency of the `uvicorn` package.
`uvicorn` was pinned to an outdated version ^0.15, I now updated it to the closest version that fixed the install which turned out to be 0.17.

**Comment by phackstock** [comment]
Let's see if the tests run through. If they do I guess we can go ahead with the merge, fix the conda publishing and then release v0.3.1.

**Review by phackstock — APPROVED** [review]
Approving the PR since the tests are passing.

**Pull request merged**
