### PR TITLE
Remove Dask and Internal Validation

### PR DESCRIPTION
**Pull request by meksor**
Provides some performance improvements by removing dask (which was causing some overhead in the benchmarks, not sure when that changed) and some internal validation. 
Functions with the @check_types validator can now take an optional argument `skip_validation` if they are used internally to avoid unnecessary pandera overhead.
Both of these adjustments made things almost 70% faster on some datasets!

### CODE REVIEW

**Review by glatterf42 — COMMENTED** [review]
This sounds super useful, though it will create a conflict with #68. And the conflict needs to be resolved, of course. Lgtm afterwards :)

**Comment by glatterf42** [comment]
Almost, now it says there's a conflict in poetry.lock.

**Comment by meksor** [comment]
Yeah because of my other PR :)

**Review by glatterf42 — APPROVED** [review]
Lgtm now :)

**Pull request merged**
